const companies = [
  "Apple",
  "Google",
  "Amazon",
  "Microsoft",
  "Facebook",
  "Tesla",
];

const randomNumbers = [
  56, -78, 90, -23, 45, -67, 12, -34, 87, 9, -5, 63, -91, 20, -42,
];

const detailedCompanies = [
  {
    name: "Apple",
    CEO: "Tim Cook",
    locatedCountry: "USA",
    industry: "Technology",
  },
  {
    name: "Google",
    CEO: "Sundar Pichai",
    locatedCountry: "USA",
    industry: "Technology",
  },
  {
    name: "Amazon",
    CEO: "Andy Jassy",
    locatedCountry: "USA",
    industry: "Technology",
  },
  {
    name: "Microsoft",
    CEO: "Satya Nadella",
    locatedCountry: "USA",
    industry: "Technology",
  },
  {
    name: "Facebook",
    CEO: "Mark Zuckerberg",
    locatedCountry: "USA",
    industry: "Technology",
  },
  {
    name: "Tesla",
    CEO: "Elon Musk",
    locatedCountry: "USA",
    industry: "Automotive",
  },
  {
    name: "BMW",
    CEO: "Oliver Zipse",
    locatedCountry: "Germany",
    industry: "Automotive",
  },
  {
    name: "Nestle",
    CEO: "Ulf Mark Schneider",
    locatedCountry: "Switzerland",
    industry: "Food and Beverage",
  },
  {
    name: "LVMH",
    CEO: "Bernard Arnault",
    locatedCountry: "France",
    industry: "Luxury Goods",
  },
  {
    name: "Siemens",
    CEO: "Roland Busch",
    locatedCountry: "Germany",
    industry: "Engineering and Electronics",
  },
  {
    name: "Volkswagen",
    CEO: "Herbert Diess",
    locatedCountry: "Germany",
    industry: "Automotive",
  },
  {
    name: "Unilever",
    CEO: "Alan Jope",
    locatedCountry: "Netherlands",
    industry: "Consumer Goods",
  },
];

const movies = [
  {
    title: "Inception",
    director: "Christopher Nolan",
    year: 2010,
    genre: "Science Fiction",
    boxOffice: 829.9,
  },
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: "Crime",
    boxOffice: 246,
  },
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    genre: "Drama",
    boxOffice: 58.3,
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    genre: "Crime",
    boxOffice: 213.9,
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    genre: "Drama",
    boxOffice: 678.2,
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: "Action",
    boxOffice: 1005,
  },
  {
    title: "The Matrix",
    director: "The Wachowskis",
    year: 1999,
    genre: "Science Fiction",
    boxOffice: 463.5,
  },
  {
    title: "Interstellar",
    director: "Christopher Nolan",
    year: 2014,
    genre: "Science Fiction",
    boxOffice: 677.5,
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    year: 2000,
    genre: "Drama",
    boxOffice: 457.6,
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    director: "Peter Jackson",
    year: 2001,
    genre: "Fantasy",
    boxOffice: 871.5,
  },
];

const movieNames = [
  "Inception",
  "The Godfather",
  "The Shawshank Redemption",
  "Pulp Fiction",
  "Forrest Gump",
  "The Dark Knight",
  "The Matrix",
  "Interstellar",
  "Gladiator",
  "The Lord of the Rings: The Fellowship of the Ring",
];

const athletes = [
  {
    name: "Usain Bolt",
    sport: "Track and Field",
    hasWorldRecord: true,
    gender: "Male",
    age: 35,
    totalMedals: 8,
    country: "Jamaica",
  },
  {
    name: "Simone Biles",
    sport: "Gymnastics",
    hasWorldRecord: false,
    gender: "Female",
    age: 25,
    totalMedals: 12,
    country: "United States",
  },
  {
    name: "Michael Phelps",
    sport: "Swimming",
    hasWorldRecord: true,
    gender: "Male",
    age: 37,
    totalMedals: 28,
    country: "United States",
  },
  {
    name: "Katie Ledecky",
    sport: "Swimming",
    hasWorldRecord: true,
    gender: "Female",
    age: 25,
    totalMedals: 10,
    country: "United States",
  },
  {
    name: "Allyson Felix",
    sport: "Track and Field",
    hasWorldRecord: false,
    gender: "Female",
    age: 36,
    totalMedals: 9,
    country: "United States",
  },
  {
    name: "Nadia Comăneci",
    sport: "Gymnastics",
    hasWorldRecord: true,
    gender: "Female",
    age: 60,
    totalMedals: 9,
    country: "Romania",
  },
  {
    name: "Birgit Fischer",
    sport: "Canoeing",
    hasWorldRecord: true,
    gender: "Female",
    age: 60,
    totalMedals: 12,
    country: "Germany",
  },
  {
    name: "Mariana Pajón",
    sport: "Cycling",
    hasWorldRecord: false,
    gender: "Female",
    age: 30,
    totalMedals: 4,
    country: "Colombia",
  },
  {
    name: "Wayne Gretzky",
    sport: "Ice Hockey",
    hasWorldRecord: false,
    gender: "Male",
    age: 61,
    totalMedals: 4,
    country: "Canada",
  },
  {
    name: "Yuna Kim",
    sport: "Figure Skating",
    hasWorldRecord: false,
    gender: "Female",
    age: 31,
    totalMedals: 6,
    country: "South Korea",
  },
];

